<?xml version="1.0" encoding="UTF-8"?><testrun name="mybatis_guanlianys" project="mybatis_guanlianys" tests="1" started="1" failures="0" errors="1" ignored="0">
  <testsuite name="top.tamlong.test.MybatisAssociatdTest" time="3.026">
    <testcase name="findPersonByIdTest" classname="top.tamlong.test.MybatisAssociatdTest" time="3.026">
      <error>org.apache.ibatis.exceptions.PersistenceException: &#13;
### Error querying database.  Cause: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

Last packet sent to the server was 0 ms ago.&#13;
### The error may exist in top/tamlong/mapper/PersonMapper.xml&#13;
### The error may involve top.tamlong.mapper.PersonMapper.findPersonById&#13;
### The error occurred while executing a query&#13;
### Cause: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

Last packet sent to the server was 0 ms ago.&#13;
	at org.apache.ibatis.exceptions.ExceptionFactory.wrapException(ExceptionFactory.java:30)&#13;
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:149)&#13;
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:140)&#13;
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectOne(DefaultSqlSession.java:76)&#13;
	at top.tamlong.test.MybatisAssociatdTest.findPersonByIdTest(MybatisAssociatdTest.java:20)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)&#13;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)&#13;
	at java.lang.reflect.Method.invoke(Unknown Source)&#13;
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)&#13;
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)&#13;
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)&#13;
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)&#13;
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)&#13;
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)&#13;
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)&#13;
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)&#13;
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)&#13;
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)&#13;
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)&#13;
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)&#13;
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)&#13;
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:89)&#13;
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:41)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:541)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:763)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:463)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:209)&#13;
Caused by: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

Last packet sent to the server was 0 ms ago.&#13;
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)&#13;
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)&#13;
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)&#13;
	at java.lang.reflect.Constructor.newInstance(Unknown Source)&#13;
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)&#13;
	at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:1074)&#13;
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2120)&#13;
	at com.mysql.jdbc.ConnectionImpl.&lt;init&gt;(ConnectionImpl.java:723)&#13;
	at com.mysql.jdbc.JDBC4Connection.&lt;init&gt;(JDBC4Connection.java:46)&#13;
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)&#13;
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)&#13;
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)&#13;
	at java.lang.reflect.Constructor.newInstance(Unknown Source)&#13;
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)&#13;
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:302)&#13;
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:282)&#13;
	at java.sql.DriverManager.getConnection(Unknown Source)&#13;
	at java.sql.DriverManager.getConnection(Unknown Source)&#13;
	at org.apache.ibatis.datasource.unpooled.UnpooledDataSource.doGetConnection(UnpooledDataSource.java:201)&#13;
	at org.apache.ibatis.datasource.unpooled.UnpooledDataSource.doGetConnection(UnpooledDataSource.java:196)&#13;
	at org.apache.ibatis.datasource.unpooled.UnpooledDataSource.getConnection(UnpooledDataSource.java:93)&#13;
	at org.apache.ibatis.datasource.pooled.PooledDataSource.popConnection(PooledDataSource.java:403)&#13;
	at org.apache.ibatis.datasource.pooled.PooledDataSource.getConnection(PooledDataSource.java:89)&#13;
	at org.apache.ibatis.transaction.jdbc.JdbcTransaction.openConnection(JdbcTransaction.java:138)&#13;
	at org.apache.ibatis.transaction.jdbc.JdbcTransaction.getConnection(JdbcTransaction.java:60)&#13;
	at org.apache.ibatis.executor.BaseExecutor.getConnection(BaseExecutor.java:336)&#13;
	at org.apache.ibatis.executor.SimpleExecutor.prepareStatement(SimpleExecutor.java:85)&#13;
	at org.apache.ibatis.executor.SimpleExecutor.doQuery(SimpleExecutor.java:62)&#13;
	at org.apache.ibatis.executor.BaseExecutor.queryFromDatabase(BaseExecutor.java:324)&#13;
	at org.apache.ibatis.executor.BaseExecutor.query(BaseExecutor.java:156)&#13;
	at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:109)&#13;
	at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:83)&#13;
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:147)&#13;
	... 26 more&#13;
Caused by: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

Last packet sent to the server was 0 ms ago.&#13;
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)&#13;
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)&#13;
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)&#13;
	at java.lang.reflect.Constructor.newInstance(Unknown Source)&#13;
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)&#13;
	at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:1074)&#13;
	at com.mysql.jdbc.MysqlIO.&lt;init&gt;(MysqlIO.java:335)&#13;
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2043)&#13;
	... 52 more&#13;
Caused by: java.net.UnknownHostException: mybatis&#13;
	at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)&#13;
	at java.net.InetAddress$2.lookupAllHostAddr(Unknown Source)&#13;
	at java.net.InetAddress.getAddressesFromNameService(Unknown Source)&#13;
	at java.net.InetAddress.getAllByName0(Unknown Source)&#13;
	at java.net.InetAddress.getAllByName(Unknown Source)&#13;
	at java.net.InetAddress.getAllByName(Unknown Source)&#13;
	at com.mysql.jdbc.StandardSocketFactory.connect(StandardSocketFactory.java:243)&#13;
	at com.mysql.jdbc.MysqlIO.&lt;init&gt;(MysqlIO.java:284)&#13;
	... 53 more&#13;
&#13;
</error>
    </testcase>
  </testsuite>
</testrun>
